# Neural Network Architecture for predicting the Credit Card Fraud 

## Importing the libraries

In [22]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [23]:
dataset=pd.read_csv('creditcard.csv')
x=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values

In [24]:
print(dataset.head(10))

   Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   
5   2.0 -0.425966  0.960523  1.141109 -0.168252  0.420987 -0.029728  0.476201   
6   4.0  1.229658  0.141004  0.045371  1.202613  0.191881  0.272708 -0.005159   
7   7.0 -0.644269  1.417964  1.074380 -0.492199  0.948934  0.428118  1.120631   
8   7.0 -0.894286  0.286157 -0.113192 -0.271526  2.669599  3.721818  0.370145   
9   9.0 -0.338262  1.119593  1.044367 -0.222187  0.499361 -0.246761  0.651583   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -

In [25]:
print(x)

[[ 0.00000000e+00 -1.35980713e+00 -7.27811733e-02 ...  1.33558377e-01
  -2.10530535e-02  1.49620000e+02]
 [ 0.00000000e+00  1.19185711e+00  2.66150712e-01 ... -8.98309914e-03
   1.47241692e-02  2.69000000e+00]
 [ 1.00000000e+00 -1.35835406e+00 -1.34016307e+00 ... -5.53527940e-02
  -5.97518406e-02  3.78660000e+02]
 ...
 [ 1.72788000e+05  1.91956501e+00 -3.01253846e-01 ...  4.45477214e-03
  -2.65608286e-02  6.78800000e+01]
 [ 1.72788000e+05 -2.40440050e-01  5.30482513e-01 ...  1.08820735e-01
   1.04532821e-01  1.00000000e+01]
 [ 1.72792000e+05 -5.33412522e-01 -1.89733337e-01 ... -2.41530880e-03
   1.36489143e-02  2.17000000e+02]]


In [26]:
print(y)

[0 0 0 ... 0 0 0]


## Splitting the dataset into the Training set and Test set 

In [27]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

## Feature Scaling

In [28]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# Building the ANN

## Initializing the ANN

In [29]:
ann = tf.keras.models.Sequential()

## Adding the input layer and the first hidden layer

In [30]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

## Adding the second hidden layer 

In [31]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

## Adding the output layer 

In [32]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Training the ANN

## Compiling the ANN 

In [33]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

## Training the ANN on the Training set

In [34]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
7121/7121 [==============================] - 10s 1ms/step - loss: 0.0712 - accuracy: 0.9799 3s - loss: 0.1031 - accuracy:  - ETA
Epoch 2/100
7121/7121 [==============================] - 8s 1ms/step - loss: 0.0033 - accuracy: 0.9994
Epoch 3/100
7121/7121 [==============================] - 8s 1ms/step - loss: 0.0029 - accuracy: 0.9995
Epoch 4/100
7121/7121 [==============================] - 8s 1ms/step - loss: 0.0039 - accuracy: 0.9993
Epoch 5/100
7121/7121 [==============================] - 8s 1ms/step - loss: 0.0032 - accuracy: 0.9995: 0s - los
Epoch 6/100
7121/7121 [==============================] - 8s 1ms/step - loss: 0.0026 - accuracy: 0.9995: 1s - loss: 0.0026 - 
Epoch 7/100
7121/7121 [==============================] - 8s 1ms/step - loss: 0.0031 - accuracy: 0.9993
Epoch 8/100
7121/7121 [==============================] - 8s 1ms/step - loss: 0.0031 - accuracy: 0.9994
Epoch 9/100
7121/7121 [==============================] - 8s 1ms/step - loss: 0.0029 - accuracy: 0.9994
Epo

7121/7121 [==============================] - 12s 2ms/step - loss: 0.0021 - accuracy: 0.9995
Epoch 76/100
7121/7121 [==============================] - 13s 2ms/step - loss: 0.0020 - accuracy: 0.9995
Epoch 77/100
7121/7121 [==============================] - 13s 2ms/step - loss: 0.0019 - accuracy: 0.9996
Epoch 78/100
7121/7121 [==============================] - 13s 2ms/step - loss: 0.0022 - accuracy: 0.9995
Epoch 79/100
7121/7121 [==============================] - 13s 2ms/step - loss: 0.0021 - accuracy: 0.9995
Epoch 80/100
7121/7121 [==============================] - 13s 2ms/step - loss: 0.0020 - accuracy: 0.9994 0s - loss: 0.0020 - accuracy
Epoch 81/100
7121/7121 [==============================] - 13s 2ms/step - loss: 0.0021 - accuracy: 0.9995
Epoch 82/100
7121/7121 [==============================] - 13s 2ms/step - loss: 0.0020 - accuracy: 0.9995
Epoch 83/100
7121/7121 [==============================] - 13s 2ms/step - loss: 0.0019 - accuracy: 0.9995
Epoch 84/100
7121/7121 [===============

# Making the predictions and evaluating the model

## Predicting the Test set results

In [35]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


## Making the Confusion Matrix

In [36]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[56854     7]
 [   26    75]]


0.999420666409185